throw new Error('Failed on purpose');